language: python
notifications:
  email: false
python:
  - "2.7"
before_install:
  - sudo apt-get install git
  - git clone https://github.com/zack-bitcoin/augur-core.git augur/core
install:
  - easy_install -U setuptools
  - pip2 install m3-cdecimal
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
before_script:
  - ./augur_ctl start &
  - python augur/core/threads.py testuser &
  - sleep 60
script:
  - py.test test/test_augur.py --doctest-modules -v --cov augur --cov-report term-missing
after_success:
  - coveralls